title: My Learning Path
description: A couple of great learning resources!
steps:
  # Point to a course on Learning Lab owned by the same user or organization as this Learning Path
  - course: introduction-to-github

  # Point to a course owned by another user on Learning Lab
  - course: githubtraining/introduction-to-github

  # Point to an external link
  - link: https://opensource.guide/starting-a-project/#writing-a-readme
    title: The ingredients of a great README 
    description: >-
      Great READMEs help users understand your project, why it matters and what they can do with it.
      This guide shares some helpful tips to write great READMEs.

  # Embed a video
  - link: https://www.youtube.com/watch?v=w3jLJU7DT5E
    video: https://www.youtube.com/watch?v=w3jLJU7DT5E
    title: What is GitHub?
    description: >-
      Hey, it's your first time here, so let's not take any chances.
      Check out this short video to understand why people use GitHub.
